config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } 

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale, exclude: /\/auth\//

  root to: 'projects#index'

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/guidelines_backers" => "static#guidelines_backers", :as => :guidelines_backers
  match "/guidelines_start" => "static#guidelines_start", :as => :guidelines_start
  match "/about" => "static#about", :as => :about
  match "/faq" => "static#faq", :as => :faq

  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'vimeo'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/:permalink" => "projects#show", as: :project_by_slug
end

app/models/backer.rb
# coding: utf-8
class Backer < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::DateHelper
  belongs_to :project
  belongs_to :user
  belongs_to :reward
  has_many :payment_notifications
  validates_presence_of :project, :user, :value
  validates_numericality_of :value, :greater_than_or_equal_to => 10.00
  validate :reward_must_be_from_project
  scope :by_id, ->(id) { where(id: id) }
  scope :by_key, ->(key) { where(key: key) }
  scope :by_user_id, ->(user_id) { where(user_id: user_id) }
  scope :user_name_contains, ->(term) { joins(:user).where("unaccent(upper(users.name)) LIKE ('%'||unaccent(upper(?))||'%')", term) }
  scope :project_name_contains, ->(term) { joins(:project).where("unaccent(upper(projects.name)) LIKE ('%'||unaccent(upper(?))||'%')", term) }
  scope :anonymous, where(:anonymous => true)
  scope :credits, where(:credits => true)
  scope :requested_refund, where(:requested_refund => true)
  scope :refunded, where(:refunded => true)
  scope :not_anonymous, where(:anonymous => false)
  scope :confirmed, where(:confirmed => true)
  scope :not_confirmed, where(:confirmed => false) # used in payment engines
  scope :in_time_to_confirm, ->() { where(%Q{date(current_timestamp) <= date(created_at + interval '5 days')}) }

  # Backers already refunded or with requested_refund should appear so that the user can see their status on the refunds list
  scope :can_refund, ->{
    where(%Q{
      confirmed AND
      EXISTS(
        SELECT true
          FROM projects p
          WHERE p.id = backers.project_id and p.state = 'failed'
      ) AND
      date(current_timestamp) <= date(created_at + interval '180 days')
    })
  }

  attr_protected :confirmed

  def refund_deadline
    created_at + 180.days
  end

  def confirm!
    self.confirmed = true
    self.save
  end

  def unconfirm!
    self.confirmed = false
    self.save
  end

  def can_refund?
    confirmed? && created_at >= (Date.today - 180.days) && project.finished? && !project.successful?
  end

  def reward_must_be_from_project
    return unless reward
    errors.add(:reward, I18n.t('backer.reward_must_be_from_project')) unless reward.project == project
  end

  validate :value_must_be_at_least_rewards_value

  def value_must_be_at_least_rewards_value
    return unless reward
    errors.add(:value, I18n.t('backer.value_must_be_at_least_rewards_value', :minimum_value => reward.display_minimum)) unless value >= reward.minimum_value
  end

  validate :should_not_back_if_maximum_backers_been_reached, :on => :create

  def should_not_back_if_maximum_backers_been_reached
    return unless reward and reward.maximum_backers and reward.maximum_backers > 0
    errors.add(:reward, I18n.t('backer.should_not_back_if_maximum_backers_been_reached')) unless reward.backers.confirmed.count < reward.maximum_backers
  end

  def display_value
    number_to_currency value, :unit => "R$", :precision => 0, :delimiter => '.'
  end

  def display_confirmed_at
    I18n.l(confirmed_at.to_date) if confirmed_at
  end

  def platform_fee(fee=7.5)
    (value.to_f * fee)/100
  end

  def display_platform_fee(fee=7.5)
    number_to_currency platform_fee(fee), :unit => "R$", :precision => 2, :delimiter => ','
  end

  def as_json(options={})
    json_attributes = {
      :id => id,
      :anonymous => anonymous,
      :confirmed => confirmed,
      :confirmed_at => display_confirmed_at,
      :value => display_value,
      :user => user.as_json(options.merge(:anonymous => anonymous)),
      :display_value => nil,
      :reward => nil
    }
    if options and options[:can_manage]
      json_attributes.merge!({
        :display_value => display_value,
        :reward => reward
      })
    end
    if options and options[:include_project]
      json_attributes.merge!({:project => project})
    end
    if options and options[:include_reward]
      json_attributes.merge!({:reward => reward})
    end
    json_attributes
  end

  # Used in payment engines
  def price_in_cents
    (self.value * 100).round
  end

  #==== Used on before and after callbacks

  def define_key
    self.update_attributes({ key: Digest::MD5.new.update("#{self.id}###{self.created_at}###{Kernel.rand}").to_s })
  end

  def define_payment_method
    self.update_attributes({ payment_method: 'MoIP' })
  end
end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  has_scope :by_user_id, :by_key, :user_name_contains, :project_name_contains, :confirmed, :credits, :requested_refund, :refunded
  before_filter :set_title

  def confirm
    resource.confirm!
    flash[:notice] = I18n.t('adm.backers.messages.successful.confirm')
    redirect_to adm_backers_path
  end

  def unconfirm
    resource.unconfirm!
    flash[:notice] = I18n.t('adm.backers.messages.successful.unconfirm')
    redirect_to adm_backers_path
  end

  protected
  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @backers = apply_scopes(Backer).order("backers.created_at DESC").page(params[:page])
  end
end

app/controllers/adm/base_controller.rb
class Adm::BaseController < ApplicationController
  inherit_resources
  before_filter do
    authorize! :manage, resource_class
  end

  @@menu_items = {}
  cattr_accessor :menu_items

  def self.menu menu=nil
    if menu
      self.menu_items.merge! menu
    else
      self.menu_items
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.json { respond_with_bip(resource) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(resource) }
      end
    end
  end
end

app/controllers/adm/financials_controller.rb
class Adm::FinancialsController < Adm::BaseController
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'
  menu I18n.t("adm.financials.index.menu") => Rails.application.routes.url_helpers.adm_financials_path
  has_scope :by_permalink, :name_contains, :user_name_contains, :financial
  actions :index

  def collection
    @search = apply_scopes(Project).includes(:project_total, :user)
    @projects = @search.order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, expires_at::date").page(params[:page])
  end
end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :order_table

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @search = apply_scopes(Project)
    @projects = @search.order('created_at DESC').page(params[:page]) unless current_scopes.include?(:order_table)
  end
end

app/controllers/adm/reports/backer_reports_controller.rb
class Adm::Reports::BackerReportsController < Adm::Reports::BaseController
  def end_of_association_chain
    super.where(project_id: params[:project_id])
  end
end

app/controllers/adm/reports/base_controller.rb
class Adm::Reports::BaseController < Adm::BaseController
  inherit_resources
  responders :csv
  respond_to :csv
  actions :index
end

app/controllers/adm/users_controller.rb
class Adm::UsersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.users.index.menu") => Rails.application.routes.url_helpers.adm_users_path
  before_filter :set_title
  before_filter :set_totals

  has_scope :by_id, :by_name, :by_email, :by_payer_email, :by_key, :has_credits, :has_credits_difference, :only => :index

  protected
  def set_totals
    totals = end_of_association_chain.backer_totals
    @total_users = totals[:users].to_i
    @total_backs = totals[:backs]
    @total_backed = totals[:backed]
    @total_credits = totals[:credits]
  end

  def set_title
    @title = t("adm.users.index.title")
  end

  def collection
    @users ||= end_of_association_chain.order_by(params[:order_by] || 'coalesce(user_totals.sum, 0) DESC').includes(:user_total).page(params[:page])
  end
end

app/controllers/backers_controller.rb
class BackersController < ApplicationController
  inherit_resources
  defaults :resource_class => Backer, :collection_name => 'backs', :instance_name => 'back'
  belongs_to :user
  actions :index
  respond_to :json, :only => [:index]

  def index
    index! do |format|
      format.json{ return render :json => @backs.includes(:user, :reward, project: [:user, :category, :project_total]).to_json({:include_project => true, :can_manage => (current_user == @user)}) }
      format.html{ return render :nothing => true, :status => 404 }
    end
  end

  protected
  def collection
    @backs = end_of_association_chain.confirmed.order("confirmed_at DESC")
    @backs = @backs.not_anonymous unless @user == current_user or (current_user and current_user.admin)
    @backs = @backs.page(params[:page]).per(10)
  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:review, :update_info]
  skip_before_filter :verify_authenticity_token, :only => [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render :json => {:message => 'updated'}
  end

  def index
    @backers = parent.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      return render :create
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/views/adm/backers/index.html.slim
#page_content
  .container
    .title
      h1= t('.title')
      h2
        strong= "#{@total_backers} "
        = t('.total_backers')
        | ·
        strong= "#{@total_backs} "
        = t('.total_backs')
        | ·
        strong= "#{number_to_currency @total_backed, :unit => 'R$', :precision => 0, :delimiter => '.'} "
        = t('.total_backed')
        | ·
        strong= "#{@total_users} "
        = t('.total_users')

    .filters
      .bootstrap-form
        = form_tag adm_backers_path, method: :get, class: 'form-horizontal' do |f|
          fieldset
            .input
              = label_tag :by_user_id, t('.user_id')
              = text_field_tag :by_user_id, params[:by_user_id], class: 'input-small'
            .input
              = label_tag :by_key, t('.key')
              = text_field_tag :by_key
            .input
              = label_tag :project_name_contains, t('.project')
              = text_field_tag :project_name_contains
            .input
              = label_tag :user_name_contains, t('.user')
              = text_field_tag :user_name_contains
            .bootstrap-twitter
              .input.submit
                = submit_tag t('.submit'), class: 'btn btn-success'
          fieldset
            .input.check
              = check_box_tag :confirmed
              = label_tag :confirmed, t('.confirmed')
            .input.check
              = check_box_tag :credits
              = label_tag :credits, t('.credits')
            .input.check
              = check_box_tag :requested_refund
              = label_tag :requested_refund, t('.requested_refund')
            .input.check
              = check_box_tag :refunded
              = label_tag :refunded, t('.refunded')
            .input.total_results
              #total_results
                = pluralize_without_number collection.count, t('found_singular'), t('found_plural')
                strong= collection.count
                = pluralize_without_number(collection.count, t('backer_singular'), t('backer_plural')).downcase
      .clearfix
      = paginate @backers
      - if @backers.empty?
        = t('.no_backers')
      - else
        .bootstrap-twitter
          table.table.table-striped
            thead
              tr
                th= t('.project')
                th= t('.user')
                th= t('.value')
                th= t('.reward')
                th= t('.key')
                th= t('.anonymous')
                th= t('.credits')
                th= t('.requested_refund')
                th= t('.refunded')
                th
            tbody
              - @backers.includes(:project, :user, :reward).each do |backer|
                tr id=backer.id class=cycle("even", "odd")
                  td title=backer.project.name
                    = link_to project_by_slug_path(permalink: backer.project.permalink) do
                      = image_tag backer.project.display_image, class: 'project_img'
                  td title=backer.user.display_name
                    = link_to user_path(backer.user) do
                      = image_tag backer.user.display_image, class: 'user_img'
                    .user_id= best_in_place [:adm, backer], :user_id, method: :put, type: :input
                  td= backer.display_value
                  td title=("#{backer.reward.display_minimum} - #{backer.reward.description}" if backer.reward)
                    - if backer.reward
                      = backer.reward.display_minimum
                    - else
                      |-
                  td.key= backer.key
                  td.checkbox= best_in_place [:adm, backer], :anonymous, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
                  td= (backer.credits ? t('yes') : t('no'))
                  td= (backer.requested_refund ? t('yes') : t('no'))
                  td.checkbox= best_in_place [:adm, backer], :refunded, type: :checkbox, collection: [t('no'), t('yes')]
                  td.bootstrap-twitter
                    .btn-group
                      = link_to 'javascript:void(0);', :"data-toggle" => 'dropdown', :class => 'btn btn-mini dropdown-toggle' do
                        span.caret
                      ul.dropdown-menu
                        - if backer.confirmed
                          li= link_to t('adm.backers.index.unconfirm_backer'), unconfirm_adm_backer_path(backer), method: :put
                        - else
                          li= link_to t('adm.backers.index.confirm_backer'), confirm_adm_backer_path(backer), method: :put
      = paginate @backers
  .clearfix