config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } 

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale, exclude: /\/auth\//

  root to: 'projects#index'

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/guidelines_backers" => "static#guidelines_backers", :as => :guidelines_backers
  match "/guidelines_start" => "static#guidelines_start", :as => :guidelines_start
  match "/about" => "static#about", :as => :about
  match "/faq" => "static#faq", :as => :faq

  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'vimeo'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/:permalink" => "projects#show", as: :project_by_slug
end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :order_table

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @search = apply_scopes(Project)
    @projects = @search.order('created_at DESC').page(params[:page]) unless current_scopes.include?(:order_table)
  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:review, :update_info]
  skip_before_filter :verify_authenticity_token, :only => [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render :json => {:message => 'updated'}
  end

  def index
    @backers = parent.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      return render :create
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper

  load_and_authorize_resource only: [ :new, :update, :update, :destroy ]

  inherit_resources
  has_scope :pg_search, :by_category_id, :recent, :expiring, :successful, :recommended, :not_expired
  respond_to :html, :except => [:backers]
  respond_to :json, :only => [:index, :show, :backers, :update]
  skip_before_filter :detect_locale, :only => [:backers]

  def index
    index! do |format|
      format.html do
        @title = t("site.title")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          if current_user and current_user.recommended_project
            @recommended_project = current_user.recommended_project
            collection_projects = collection_projects.where("id != ? AND category_id != ?", current_user.recommended_project.id, @recommended_project.category_id)
          end
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }
        project_ids << @recommended_project.id if @recommended_project

        @expiring = Project.expiring_for_home(project_ids)
        @recent = Project.recent_for_home(project_ids)
        @blog_posts = blog_posts
        @last_tweets = last_tweets
      end

      format.json do
        @projects = apply_scopes(Project).visible.order_for_search
        respond_with(@projects.includes(:project_total, :user, :category).page(params[:page]).per(6))
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    create!(:notice => t('projects.create.success'))
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attributes({ short_url: bitly })
    end
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.find_by_permalink! params[:permalink]
      else
        return redirect_to project_by_slug_path(resource.permalink)
      end

      show!{
        @title = @project.name
        @rewards = @project.rewards.includes(:project).order(:minimum_value).all
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
        @update = @project.updates.where(:id => params[:update_id]).first if params[:update_id].present?
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo.info
      render :json => project.vimeo.info.to_json
    else
      render :json => {:id => false}.to_json
    end
  end

  def check_slug
    project = Project.where("permalink = ?", params[:permalink])
    render :json => {:available => project.empty?}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  private
  def last_tweets
    Rails.cache.fetch('last_tweets', :expires_in => 30.minutes) do
      begin
        JSON.parse(Net::HTTP.get(URI("http://api.twitter.com/1/statuses/user_timeline.json?screen_name=#{::Configuration[:twitter_username]}")))[0..1]
      rescue
        []
      end
    end
  end

  def blog_posts
    Blog.fetch_last_posts.inject([]) do |total,item|
      total << item if total.size < 2
      total
    end
  rescue
    []
  end

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=#{Configuration[:bitly_api_login]}&apiKey=#{Configuration[:bitly_api_key]}&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end
end

app/views/projects/_backer.html.slim
script type="text/template" id="empty_backers_template"
  p= t('projects.project_backers.empty')

script type="text/template" id="backers_template"
  ul.collection_list

script type="text/template" id="backer_template"
  .backer
    | <% if(anonymous) { %>
    img src="/assets/user.png" class="backer_avatar"
    .back_info
      p#text
        em.anon=" #{t('.anonymous_backer')}"
      p#confirmed
        | <%= confirmed_at %>
      p#backed= t('.anonymous_description')
    | <% } else { %>
    a href="<%= user['url'] %>"
      img src="<%= user['image'] %>" class="backer_avatar"
    .back_info
      p#text
        a href="<%= user['url'] %>"
         | <%= user['short_name'] %>
      p#confirmed
        | <%= confirmed_at %>
      p#backed
        | <%= user['backs_text'] %>
    | <% } %>
    - if current_user and (current_user == @project.user or current_user.admin)
      .reward
        =
        .value <%= value %> .
        | <% if (reward) { %>
        .user_reward <%= reward['display_minimum'] %> - <%= reward['medium_description'] %>
        | <% } else { %>
        | &nbsp;
        = t('.no_reward')
        | <% } %>
        | <% if(user['email']) { %>
        .user_email <%= user['email'] %>
        | <% } else { %>
        | &nbsp;
        = t('not_informed')
        |.
        | <% } %>
        
    .clear

app/views/projects/_box.html.slim
.project[itemscope itemtype="http://schema.org/CreativeWork" class=(custom_class if defined?(custom_class))]
  meta[itemprop="dateCreated" content=project.created_at.to_date]
  - if project.expired?
    .status_image
      = link_to project_by_slug_path(permalink: project.permalink), :target => ( defined?(embed_link) ? '__blank' : '' ) do
        - if project.successful?
          = image_tag "successful.#{I18n.locale}.png"
        - elsif project.waiting_confirmation?
          = image_tag "waiting_confirmation.#{I18n.locale}.png"
        - else
          = image_tag "not_successful.#{I18n.locale}.png"
  .box
    p.black_box= project.category
    .cover
      = link_to project, :target => ( defined?(embed_link) ? '__blank' : '' ) do
        = image_tag project.display_image, :itemprop => 'image'
    .project_content
      h4= link_to project, :target => ( defined?(embed_link) ? '__blank' : '' ), :itemprop => 'url' do
        span[itemprop="name"]= project.name
      p.author
        = t('.by')
        |&nbsp;
        span[itemprop="author"]= project.user.name
      p.description[itemprop="description"]= truncate(project.headline, :length => 140)
      p.where[itemprop="contentLocation"]
        - unless project.user.address_city.blank?
          = project.user.address_city
          - unless project.user.address_state.blank?
            | /
            = project.user.address_state
    .info_bar
      .status_bar
        .progress style="width: #{project.display_progress}%;"
      ul
        li
          - if project.in_time?
            h6= "#{project.time_to_go[:time]} #{project.time_to_go[:unit]}"
            p= "#{project.remaining_text}"
          - else
            h6= I18n.t("project.display_status.#{project.display_status}").capitalize
            p= project.display_expires_at
        li
          h6= "#{project.display_pledged}"
          p= "#{t('projects.project.backed')}"

        li
          h6= "#{project.progress}%"
          p= "#{t('projects.project.reached')}"

app/views/projects/_comments.html.slim
.fb-comments[data-href=request.url data-num-posts=50 data-width="610"]

app/views/projects/_formatting_tips.pt.html.slim
#show_formatting_tips
  | Quer usar imagens, vídeos, links e formatação?
  a href="#" Clique aqui
  | .
#formatting_tips
  h3 Saiba como você pode formatar seu comentário
  ul
    li
      | Se você colar a URL de uma imagem ou de um vídeo do Vimeo ou do YouTube, eles irão aparecer no comentário. Experimente!
    li
      | Ao colar uma URL qualquer, ela virará um link. Por exemplo, http://catarse.me virará
      a href="#{Configuration[:base_url]}" target="_blank" #{Configuration[:base_url]}
      | .
    li
      | Se você quiser colocar um texto no link, basta usar o seguinte formato:
      strong "texto que você quer":http://sua.url
      | . Por exemplo, "#{Configuration[:company_name]}":http://catarse.me virará
      a href="#{Configuration[:base_url]}" target="_blank" #{Configuration[:company_name]}
      | .
    li
      | Você pode usar
      strong negrito
      | adicionando um asterisco (*) antes e depois do texto que você quer formatar. Por exemplo, *meu texto em negrito* irá aparecer como
      strong meu texto em negrito
      | .
    li
      | Você pode usar
      em itálico
      | adicionando um underline (_) antes e depois do texto que você quer formatar. Por exemplo, _meu texto em itálico_ irá aparecer como
      em meu texto em itálico
      | .

app/views/projects/_project.html.slim
div class="curated_project #{(defined?(has_comments) ? :compost_project : '')}"
  = render 'projects/box', project: project, custom_class: (custom_class if defined?(custom_class))
  - if defined?(has_comments)
    .project_comment
      h3= "#{(defined?(comments_title) ? comments_title : project.category)}"
      p= "#{project.home_page_comment}"
  - if defined?(project_curated_page) and project_curated_page.count > 0 and project_curated_page.first.description.present?
    .project_curator_description
      == project_curated_page.first.description_html

app/views/projects/_project_header.html.slim
.video_sample
  iframe src="#{project.vimeo.embed_url}?title=0&amp;byline=0&amp;portrait=0&amp" width="461" height="258" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
.info
  h3= title
  h2
    = link_to project.name, project_by_slug_path(permalink: project.permalink)
  .author
    p
      = t('projects.box.by')
      |&nbsp;
      = link_to project.user.name, user_path(project.user)
  .description
    p= link_to truncate(project.headline, :length => 120), project_by_slug_path(permalink: project.permalink)
  .author
    - if project.user.address_city || project.user.address_state
      p= link_to 'javascript:void(0)' do
        - unless project.user.address_city.blank?
          = project.user.address_city
        - unless project.user.address_state.blank?
            | &nbsp; / &nbsp;
            = project.user.address_state
  .statistics
    .progress
      .bar[style="width: #{project.display_progress}%"]
    ul
      li
        strong= "#{project.time_to_go[:time]} #{project.time_to_go[:unit]}"
        p= "#{project.remaining_text}"
      li
        strong= "#{project.progress}%"
        p="#{t('projects.project.reached')}"
      li.last
        strong= "#{project.display_pledged}"
        p= "#{t('projects.project.backed')}"

app/views/projects/_project_templates.html.slim
script type="text/template" id="project_video_embed"
  iframe src="<%= embed_url %>?title=0&amp;byline=0&amp;portrait=0&amp" width="640" height="430" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen

script type="text/template" id="project_reward_maximum_backers_label"
  .limited
    | Limitada
  .remaining
    | <%= remaining %> de
    span class="best_in_place" id="best_in_place_reward_<%=id%>_maximum_backers" data-url="/pt/projects/<%= project_id %>/rewards/<%= id %>" data-object="reward" data-attribute="maximum_backers" data-type="input"
      | &nbsp; <%= maximum_backers %> &nbsp;
    | disponíveis

app/views/projects/_recommended_header.html.slim
#recommended_header
  .resume_about
    = image_tag "catarse/box_#{I18n.locale}.jpg"
    .bootstrap-form
      = form_tag(guidelines_path, :method => :get, :id => 'guidelines_form') do
        fieldset
          .bootstrap-twitter
            .button
              = link_to t('.guidelines'), guidelines_path, :class=>'btn_explore'
              span = t('.guidelines_subtitle')
  .project_info
    - if current_user
      - if @recommended_project
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.suggest_for_you'), :project => @recommended_project} if @recommended_project
      - else
        = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
    - else
      = render :partial => "project_header", :locals => {:title => t('projects.recommended_header.highlight_project'), :project => @fourth_project} if @fourth_project
  .clearfix

app/views/projects/_show_embed.html.slim
- box_width = "240px"
- box_height = "415px"
- video_width = "384px"
- video_height = "415px"
#embed_overlay.overlay.hide
  #project_embed.hide
    a.close href='javascript:CATARSE.router.back()' X
    #project_box_embed
      iframe frameborder='0' height=box_height width=box_width src=embed_project_path(@project)
      form.html= text_area_tag 'project_box_embed_html', '<iframe frameborder="0" height="' + box_height + '" src="' + embed_project_url(@project) + '" width="' + box_width + '"></iframe>', :readonly => true
    #project_video_embed
      iframe frameborder='0' height=video_height width=video_width src=video_embed_project_path(@project)
      form.html= text_area_tag 'project_video_embed_html', '<iframe frameborder="0" height="' + video_height + '" src="' + video_embed_project_url(@project) + '" width="' + video_width + '"></iframe>', :readonly => true
    .clearfix

app/views/projects/embed.html.slim
#embed
  = render :partial => 'box', :locals => { :project => @project, :embed_link => true }

app/views/projects/index.html.slim
= render :partial => 'recommended_header'
#page_content
  .container
    .main
      .selected_projects.list
        .list_title
          .title
            h2= t('sections.selection.title')
        .projects
          = render :partial => 'project', :locals => {:project => @first_project, :custom_class => 'first' } if @first_project
          = render :partial => 'project', :locals => {:project => @second_project } if @second_project
          = render :partial => 'project', :locals => {:project => @third_project, :custom_class => 'last' } if @third_project
        .explore_link
          hr
          = link_to t('main.links.selected'), explore_path()+"#recommended"

      .expiring_projects.list
        .list_title
          .title
            h2= t('sections.expiring.title')
        .projects
          - @expiring.each_with_index do |item,i|
            == render 'project', :project => item, :custom_class => ((@expiring.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
        .explore_link
          hr
          = link_to t('main.links.expiring'), explore_path()+'#expiring'

      .recents_projects.list
        .list_title
          .title
            h2= t('sections.recents.title')
        .projects
          - @recent.each_with_index do |item,i|
            == render 'project', :project => item, :custom_class => ((@recent.length == (i+1) ? 'last' : false) || (i==0 ? 'first' : false))
        .explore_link
          hr
          = link_to t('main.links.recents'), explore_path()+'#recent'

    .sidebar
      .content
        .blog
          h3= t('sidebar.titles.blog')
          ul.posts
            - @blog_posts.each do |post|
              li
                h2
                  = link_to post.url, target: '__blank' do
                    /= image_tag("catarse/post_title_image.png")
                    = truncate(post.title, length: 80)
                p.author= "#{t('projects.box.by')} #{post.author}"
                = link_to post.url, target: '__blank', class: 'resume' do
                  = truncate(post.summary, length: 130).html_safe

        .facebook
          h3= t('sidebar.titles.facebook')
          .fb-like data-href="#{Configuration['facebook_url']}" data-send="false" data-width="171" data-show-faces="true"
        .twitter
          h3= "@#{Configuration['twitter_username']}"
          - @last_tweets.each do |tweet|
            p= tweet['text']
          = link_to "Follow @#{Configuration['twitter_username']}", "http://twitter.com/#{Configuration['twitter_username']}", :class => 'twitter-follow-button', :"data-show-count" => "false" , :"data-button"=>"blue", :"data-text-color" => "#ffffff", :"data-link-color"=>"#fffffff", :"data-width" => "224px"
        .newsletter
          h3= t('sidebar.titles.newsletter')
          = form_tag Configuration['mailchimp_url'], id: 'mailee-form', method: 'post' do
            = text_field_tag 'EMAIL', nil, placeholder: 'email@email.com', label: 'email'
            = submit_tag t('sidebar.buttons.newsletter')
    .clearfix

app/views/projects/new.html.slim
#page_content
  .container
    .start_content
      .title
        h1= t('.title')
        h2= t('.subtitle')
        p= t('.legend_html')
      .bootstrap-form
        .clearfix
        = semantic_form_for @project, :html => { :id => 'project_form' } do |form|
          = form.inputs do
            = form.input :user_id, :as => :hidden, :value => current_user.id
            /= form.input :permalink, :as => :string
            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.permalink_important')
              = form.label :permalink, "#{t('activerecord.attributes.project.permalink')} *"
              .input-prepend.permalink
                span.add-on= "#{::Configuration[:base_url]}/"
                = form.text_field :permalink, :class => 'permalink'
                p.inline-hints
                  = t('.permalink_hint')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.name_important')
              = form.label :name, t('formtastic.labels.project.name')
              = form.text_field :name
              p.inline-hints= t('formtastic.hints.project.name')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.about_important')
              = form.label :about, t('formtastic.labels.project.about')
              = form.text_area :about
              p.inline-hints= t('formtastic.hints.project.about')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.headline_important')
              = form.label :headline, t('formtastic.labels.project.headline')
              = form.text_field :headline, { :maxlength => 140 }
              p.inline-hints= t('formtastic.hints.project.headline')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.tags_important', :href => "http://www.catarse.me/explore").html_safe
              = form.label :category, t('.category')
              = form.select :category_id, Category.array
              p.inline-hints= t('formtastic.hints.project.category')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.important_html', :link => link_to("MoIP", "http://www.moip.com.br/", :target => :_blank))
              = form.label :goal, t('formtastic.labels.project.goal')
              = form.text_field :goal
              p.inline-hints= t('formtastic.hints.project.goal').html_safe

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.online_days_important')
              = form.label :online_days, t('formtastic.labels.project.expires_at')
              .input-append
                = form.text_field :online_days
                span.add-on= t('days')
              p.inline-hints= t('formtastic.hints.project.online_days')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.video_important')
              = form.label :video_url, t('formtastic.labels.project.video_url')
              = form.text_field :video_url
              p.inline-hints= t('formtastic.hints.project.video_url').html_safe

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.more_links_important')
              = form.label :more_links, t('formtastic.labels.project.more_links')
              = form.text_area :more_links
              p.inline-hints= t('formtastic.hints.project.more_links')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.first_backers_important')
              = form.label :first_backers, t('formtastic.labels.project.first_backers')
              = form.text_area :first_backers
              p.inline-hints= t('formtastic.hints.project.first_backers')

            .input
              .bootstrap-alert
                span
                .alert
                  .important= t('.how_know_important')
              = form.label :how_know, t('formtastic.labels.project.how_know')
              = form.text_area :how_know



            .clearfix
            .submit
              fieldset.accept
                = check_box_tag 'accept'
                = label_tag 'accept', t('accept_terms_html', :link => link_to(t('terms'), t('footer.links.terms_link'), :target => :_blank)), :class => 'inline'
              fieldset
                .bootstrap-twitter
                  .send
                    = submit_tag t('.submit'), :disabled => true, :id => 'project_submit', :class => 'btn_send'
                    span = t('.send_project')
                  /= form.submit t('.submit'), :disabled => true, :class => 'btn-large btn-block btn btn-warning', :id => 'project_submit', :style => 'width: 100%;'

    .clearfix