config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } 

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale, exclude: /\/auth\//

  root to: 'projects#index'

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/guidelines_backers" => "static#guidelines_backers", :as => :guidelines_backers
  match "/guidelines_start" => "static#guidelines_start", :as => :guidelines_start
  match "/about" => "static#about", :as => :about
  match "/faq" => "static#faq", :as => :faq

  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'vimeo'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/:permalink" => "projects#show", as: :project_by_slug
end

app/controllers/adm/backers_controller.rb
class Adm::BackersController < Adm::BaseController
  menu I18n.t("adm.backers.index.menu") => Rails.application.routes.url_helpers.adm_backers_path
  has_scope :by_user_id, :by_key, :user_name_contains, :project_name_contains, :confirmed, :credits, :requested_refund, :refunded
  before_filter :set_title

  def confirm
    resource.confirm!
    flash[:notice] = I18n.t('adm.backers.messages.successful.confirm')
    redirect_to adm_backers_path
  end

  def unconfirm
    resource.unconfirm!
    flash[:notice] = I18n.t('adm.backers.messages.successful.unconfirm')
    redirect_to adm_backers_path
  end

  protected
  def set_title
    @title = t("adm.backers.index.title")
  end

  def collection
    @backers = apply_scopes(Backer).order("backers.created_at DESC").page(params[:page])
  end
end

app/controllers/adm/base_controller.rb
class Adm::BaseController < ApplicationController
  inherit_resources
  before_filter do
    authorize! :manage, resource_class
  end

  @@menu_items = {}
  cattr_accessor :menu_items

  def self.menu menu=nil
    if menu
      self.menu_items.merge! menu
    else
      self.menu_items
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.json { respond_with_bip(resource) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(resource) }
      end
    end
  end
end

app/controllers/adm/financials_controller.rb
class Adm::FinancialsController < Adm::BaseController
  inherit_resources
  defaults  resource_class: Project, collection_name: 'projects', instance_name: 'project'
  menu I18n.t("adm.financials.index.menu") => Rails.application.routes.url_helpers.adm_financials_path
  has_scope :by_permalink, :name_contains, :user_name_contains, :financial
  actions :index

  def collection
    @search = apply_scopes(Project).includes(:project_total, :user)
    @projects = @search.order("CASE state WHEN 'successful' THEN 1 WHEN 'waiting_funds' THEN 2 ELSE 3 END, expires_at::date").page(params[:page])
  end
end

app/controllers/adm/projects_controller.rb
class Adm::ProjectsController < Adm::BaseController
  menu I18n.t("adm.projects.index.menu") => Rails.application.routes.url_helpers.adm_projects_path

  has_scope :by_id, :pg_search, :user_name_contains, :order_table

  before_filter do
    @total_projects = Project.count
  end

  [:approve, :reject, :push_to_draft].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}!")
      redirect_to :back
    end
  end

  def collection
    @search = apply_scopes(Project)
    @projects = @search.order('created_at DESC').page(params[:page]) unless current_scopes.include?(:order_table)
  end
end

app/controllers/adm/reports/backer_reports_controller.rb
class Adm::Reports::BackerReportsController < Adm::Reports::BaseController
  def end_of_association_chain
    super.where(project_id: params[:project_id])
  end
end

app/controllers/adm/reports/base_controller.rb
class Adm::Reports::BaseController < Adm::BaseController
  inherit_resources
  responders :csv
  respond_to :csv
  actions :index
end

app/controllers/adm/users_controller.rb
class Adm::UsersController < Adm::BaseController
  inherit_resources
  menu I18n.t("adm.users.index.menu") => Rails.application.routes.url_helpers.adm_users_path
  before_filter :set_title
  before_filter :set_totals

  has_scope :by_id, :by_name, :by_email, :by_payer_email, :by_key, :has_credits, :has_credits_difference, :only => :index

  protected
  def set_totals
    totals = end_of_association_chain.backer_totals
    @total_users = totals[:users].to_i
    @total_backs = totals[:backs]
    @total_backed = totals[:backed]
    @total_credits = totals[:credits]
  end

  def set_title
    @title = t("adm.users.index.title")
  end

  def collection
    @users ||= end_of_association_chain.order_by(params[:order_by] || 'coalesce(user_totals.sum, 0) DESC').includes(:user_total).page(params[:page])
  end
end

app/controllers/projects/backers_controller.rb
class Projects::BackersController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update_info, :review, :create
  skip_before_filter :force_http, only: [:review, :update_info]
  skip_before_filter :verify_authenticity_token, :only => [:moip]
  load_and_authorize_resource
  belongs_to :project

  def update_info
    resource.update_attributes(params[:backer])
    render :json => {:message => 'updated'}
  end

  def index
    @backers = parent.backers.confirmed.order("confirmed_at DESC").page(params[:page]).per(10)
    render :json => @backers.to_json(:can_manage => can?(:update, @project))
  end

  def show
    @title = t('projects.backers.show.title')
  end

  def new
    unless parent.online?
      flash[:failure] = t('projects.back.cannot_back')
      return redirect_to :root
    end

    @create_url = ::Configuration[:secure_review_host] ?
      project_backers_url(@project, {:host => ::Configuration[:secure_review_host], :protocol => 'https'}) :
      project_backers_path(@project)

    @title = t('projects.backers.new.title', :name => @project.name)
    @backer = @project.backers.new(:user => current_user)
    empty_reward = Reward.new(:id => 0, :minimum_value => 0, :description => t('projects.backers.new.no_reward'))
    @rewards = [empty_reward] + @project.rewards.order(:minimum_value)
    @reward = @project.rewards.find params[:reward_id] if params[:reward_id]
    @reward = nil if @reward and @reward.sold_out?
    if @reward
      @backer.reward = @reward
      @backer.value = "%0.0f" % @reward.minimum_value
    end
  end

  def create
    @title = t('projects.backers.create.title')
    @backer.reward_id = nil if params[:backer][:reward_id].to_s == '0'
    @backer.user = current_user
    create! do |success,failure|
      failure.html do
        flash[:failure] = t('projects.backers.review.error')
        return redirect_to new_project_backer_path(@project)
      end
      return render :create
    end
    @thank_you_id = @project.id
  end

  def credits_checkout
    if current_user.credits < @backer.value
      flash[:failure] = t('projects.backers.checkout.no_credits')
      return redirect_to new_project_backer_path(@backer.project)
    end

    unless @backer.confirmed
      @backer.update_attributes({ payment_method: 'Credits' })
      @backer.confirm!
    end
    flash[:success] = t('projects.backers.checkout.success')
    redirect_to project_backer_path(project_id: parent.id, id: resource.id)
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  include ActionView::Helpers::DateHelper

  load_and_authorize_resource only: [ :new, :update, :update, :destroy ]

  inherit_resources
  has_scope :pg_search, :by_category_id, :recent, :expiring, :successful, :recommended, :not_expired
  respond_to :html, :except => [:backers]
  respond_to :json, :only => [:index, :show, :backers, :update]
  skip_before_filter :detect_locale, :only => [:backers]

  def index
    index! do |format|
      format.html do
        @title = t("site.title")
        collection_projects = Project.recommended_for_home
        unless collection_projects.empty?
          if current_user and current_user.recommended_project
            @recommended_project = current_user.recommended_project
            collection_projects = collection_projects.where("id != ? AND category_id != ?", current_user.recommended_project.id, @recommended_project.category_id)
          end
          @first_project, @second_project, @third_project, @fourth_project = collection_projects.all
        end

        project_ids = collection_projects.map{|p| p.id }
        project_ids << @recommended_project.id if @recommended_project

        @expiring = Project.expiring_for_home(project_ids)
        @recent = Project.recent_for_home(project_ids)
        @blog_posts = blog_posts
        @last_tweets = last_tweets
      end

      format.json do
        @projects = apply_scopes(Project).visible.order_for_search
        respond_with(@projects.includes(:project_total, :user, :category).page(params[:page]).per(6))
      end
    end
  end

  def new
    new! do
      @title = t('projects.new.title')
      @project.rewards.build
    end
  end

  def create
    params[:project][:expires_at] += (23.hours + 59.minutes + 59.seconds) if params[:project][:expires_at]
    validate_rewards_attributes if params[:project][:rewards_attributes].present?
    create!(:notice => t('projects.create.success'))
    # When it can't create the project the @project doesn't exist and then it causes a record not found
    # because @project.reload *works only with created records*
    unless @project.new_record?
      @project.reload
      @project.update_attributes({ short_url: bitly })
    end
  end

  def show
    begin
      if params[:permalink].present?
        @project = Project.find_by_permalink! params[:permalink]
      else
        return redirect_to project_by_slug_path(resource.permalink)
      end

      show!{
        @title = @project.name
        @rewards = @project.rewards.includes(:project).order(:minimum_value).all
        @backers = @project.backers.confirmed.limit(12).order("confirmed_at DESC").all
        fb_admins_add(@project.user.facebook_id) if @project.user.facebook_id
        @update = @project.updates.where(:id => params[:update_id]).first if params[:update_id].present?
      }
    rescue ActiveRecord::RecordNotFound
      return render_404
    end
  end

  def vimeo
    project = Project.new(:video_url => params[:url])
    if project.vimeo.info
      render :json => project.vimeo.info.to_json
    else
      render :json => {:id => false}.to_json
    end
  end

  def check_slug
    project = Project.where("permalink = ?", params[:permalink])
    render :json => {:available => project.empty?}.to_json
  end

  def embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  def video_embed
    @project = Project.find params[:id]
    @title = @project.name
    render :layout => 'embed'
  end

  private
  def last_tweets
    Rails.cache.fetch('last_tweets', :expires_in => 30.minutes) do
      begin
        JSON.parse(Net::HTTP.get(URI("http://api.twitter.com/1/statuses/user_timeline.json?screen_name=#{::Configuration[:twitter_username]}")))[0..1]
      rescue
        []
      end
    end
  end

  def blog_posts
    Blog.fetch_last_posts.inject([]) do |total,item|
      total << item if total.size < 2
      total
    end
  rescue
    []
  end

  # Just to fix a minor bug,
  # when user submit the project without some rewards.
  def validate_rewards_attributes
    rewards = params[:project][:rewards_attributes]
    rewards.each do |r|
      rewards.delete(r[0]) unless Reward.new(r[1]).valid?
    end
  end

  def bitly
    return unless Rails.env.production?
    require 'net/http'
    res = Net::HTTP.start("api.bit.ly", 80) { |http| http.get("/v3/shorten?login=#{Configuration[:bitly_api_login]}&apiKey=#{Configuration[:bitly_api_key]}&longUrl=#{CGI.escape(project_url(@project))}") }
    data = JSON.parse(res.body)['data']
    data['url'] if data
  end
end

app/views/adm/projects/index.html.slim
#page_content
  .container
    .title
      h1= t('.title')
      h2
        strong= "#{@total_projects} "
        = t('.total_projects')

    .filters
      .bootstrap-form
        = form_tag adm_projects_path, method: :get, class: 'form-horizontal' do |f|
          fieldset
            .input
              = label_tag :by_id, t('.id')
              = text_field_tag :by_id, params[:by_id], class: 'input-small'

            .input
              = label_tag :pg_search, t('.project')
              = text_field_tag :pg_search, params[:pg_search]
            .input
              = label_tag :user_name_contains, t('.user')
              = text_field_tag :user_name_contains, params[:user_name_contains]
            .input
              = label_tag :order_table, t('.order_table')
              select#order_goal name="order_table"
                option value=''
                option value='asc'= t('.order_asc')
                option value='desc'= t('.order_desc')

            .bootstrap-twitter
              .input.submit
                = submit_tag t('.submit'), class: 'btn btn-success'
          fieldset
            .input.total_results
              #total_results
                = pluralize_without_number @search.count, t('found_singular'), t('found_plural')
                strong= @search.count
                = pluralize_without_number(@search.count, t('project_singular'), t('project_plural')).downcase
      .clearfix
    .data-table
      = paginate @projects
      - if @projects.empty?
        = t('.no_backers')
      - else
        .bootstrap-twitter
          table.table.table-striped
            thead
              tr
                th style="width: 200px;"
                  = t('.name')
                th= t('.category')
                th= t('.user_id')
                th= t('.goal')
                th= t('.pledged')
                th= t('.total_backs')
                th= t('.recommended')
                th= t('.online_date')
                th= t('.expires_at')
                th= t('.state')
                th
            tbody
              - @projects.includes(:category).each do |project|
                tr id=project.id class=cycle("even", "odd")
                  td= link_to project.name, project_by_slug_path(permalink: project.permalink)
                  td= project.category
                  td= best_in_place [:adm, project], :user_id, method: :put, type: :input
                  td= best_in_place [:adm, project], :goal, method: :put, type: :input, display_as: :display_goal
                  td= "#{project.display_pledged} (#{project.progress}%)"
                  td= project.total_backers
                  td.checkbox= best_in_place [:adm, project], :recommended, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
                  td= project.online_date.strftime('%d/%m/%Y') if project.online_date
                  td= project.display_expires_at
                  td
                    - if project.online?
                      span.label.label-online= project.state
                    - elsif project.successful?
                      span.label.label-success= project.state
                    - elsif project.failed? or project.rejected?
                      span.label.label-important= project.state
                    - elsif project.waiting_funds?
                      span.label.label-warning= project.state
                    - else
                      span.label= project.state
                  td
                    .btn-group
                      = link_to 'javascript:void(0);', :class => 'btn btn-mini dropdown-toggle', :"data-toggle"=> "dropdown" do
                        b.caret
                      ul.dropdown-menu
                        - if project.can_approve?
                          li
                            = link_to approve_adm_project_path(project), :method => :put do
                              i.icon-ok
                              = t('.approve')

                        - if project.can_reject?
                          li
                            = link_to reject_adm_project_path(project), :method => :put  do
                              i.icon-ban-circle
                              = t('.reject')

                        - if project.can_push_to_draft?
                          li
                            = link_to  push_to_draft_adm_project_path(project), :method => :put  do
                              i.icon-trash
                              = t('.send_to_draft')
      = paginate @projects
  .clearfix