config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } 

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Non production routes
  if Rails.env == "development"
    resources :emails, :only => [ :index ]
  end

  mount CatarsePaypalExpress::Engine => "/", :as => "catarse_paypal_express"
  mount CatarseMoip::Engine => "/", :as => "catarse_moip"

  filter :locale, exclude: /\/auth\//

  root to: 'projects#index'

  # Static Pages
  match '/sitemap' => "static#sitemap", :as => :sitemap
  match "/guidelines" => "static#guidelines", :as => :guidelines
  match "/guidelines_tips" => "static#guidelines_tips", :as => :guidelines_tips
  match "/guidelines_backers" => "static#guidelines_backers", :as => :guidelines_backers
  match "/guidelines_start" => "static#guidelines_start", :as => :guidelines_start
  match "/about" => "static#about", :as => :about
  match "/faq" => "static#faq", :as => :faq

  match "/explore" => "explore#index", :as => :explore
  match "/explore#:quick" => "explore#index", :as => :explore_quick
  match "/credits" => "credits#index", :as => :credits

  match "/reward/:id" => "rewards#show", :as => :reward
  resources :posts, only: [:index, :create]

  namespace :reports do
    resources :backer_reports_for_project_owners, only: [:index]
  end

  resources :projects do
    resources :updates, only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy ]
    resources :backers, controller: 'projects/backers', only: [ :index, :show, :new, :create ] do
      member do
        match 'credits_checkout'
        post 'update_info'
      end
    end
    collection do
      get 'vimeo'
      get 'check_slug'
    end
    member do
      put 'pay'
      get 'embed'
      get 'video_embed'
    end
  end
  resources :users do
    resources :backers, :only => [:index]
    resources :unsubscribes, :only => [:create]
    member do
      get 'projects'
      get 'credits'
      put 'unsubscribe_update'
    end
  end
  match "/users/:id/request_refund/:back_id" => 'users#request_refund'

  resources :credits, only: [:index] do
    collection do
      get 'buy'
      post 'refund'
    end
  end

  namespace :adm do
    resources :projects, only: [ :index, :update ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
      end
    end

    resources :financials, only: [ :index ]

    resources :backers, only: [ :index, :update ] do
      member do
        put 'confirm'
        put 'unconfirm'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :backer_reports, only: [ :index ]
    end
  end

  match "/:permalink" => "projects#show", as: :project_by_slug
end

app/views/layouts/_analytics.html.slim
- if Configuration['google_analytics_id'].present?
  javascript:
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '#{Configuration['google_analytics_id']}']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

app/views/layouts/_facebook_like.html.slim
.facebook
  .fb-like data-href=href data-send="false" data-width="#{defined?(width) ? width : '260'}" data-show-faces="true"

app/views/layouts/_facebook_sdk.html.slim
#fb-root
javascript:
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '#{Configuration['facebook_app_id']}', // App ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/#{t('facebook_locale')}/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

app/views/layouts/_flash.html.slim
.flash
  - for key, msg in flash
    div class="#{key} wrapper"
      div class=key
        == msg

app/views/layouts/_header.html.slim
#header
  = link_to "Home", root_path, :class => 'logo', :title => Configuration[:company_name]
  nav.actions
    = link_to t('layouts.header.explore'), explore_path, :class => 'explore'
    = link_to t('layouts.header.submit_project'), guidelines_start_path, :class =>  'submit_project'
  .search
    = form_tag explore_path(:anchor => "search"), :method => 'GET', :class=>'search_input' do
      = text_field_tag :search, nil, autocomplete: "off"
      = submit_tag
  nav.menu
    = link_to t('layouts.header.help'), guidelines_start_path, id: 'guidelines_header_modal'
    = link_to t('layouts.header.blog'), Configuration['blog_url'], target: :_blank if Configuration['blog_url'].present?
    - if current_user
      = link_to '#', class: 'my_profile_link' do
        = image_tag(current_user.display_image, :size => "30x30", :class => 'profile_picture')
        span.current_user_name= t('layouts.header.account')
        = image_tag('dropdown.png', :class => 'dropdown_arrow')
      ul.dropdown.user
        li= link_to t('layouts.header.profile'), current_user
        li
          = link_to t('layouts.user.my_credits'), user_path(current_user, anchor: 'credits')
          .small (#{current_user.display_credits})
        li.divider
        - if current_user.admin?
          - for menu, path in Adm::BaseController.menu do
            li= link_to menu, path
        li.divider
        li= link_to t('layouts.user.logout'), destroy_user_session_path, method: :delete
    - else
      = link_to t('layouts.header.signup'), new_user_session_path(active_register: true)
      = link_to t('layouts.header.signin'), new_user_session_path
  .clearfix

app/views/layouts/_locales.html.slim
- if request.method == "GET"
  #locales class=("notify" if flash[:locale])
    ul
      - I18n.available_locales.map(&:to_s).sort.each do |locale|
        li
          = link_to params.merge(locale: locale) do
            = image_tag "locales/#{locale}.png"

app/views/layouts/_twitter.html.erb
<a href="http://twitter.com/share" class="twitter-share-button" data-count="<%= (defined?(count) ? count : 'horizontal') %>" data-text="<%= (defined?(text) ? text : t('.take_a_look', :name => @project.name) ) %>" data-url="<%= (defined?(url) ? url : request.url) %>">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

app/views/layouts/_uservoice.html.slim
javascript:
  var uvOptions = {};
  (function() {
    var uv = document.createElement('script'); uv.type = 'text/javascript'; uv.async = true;
    uv.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'widget.uservoice.com/N0ybFnQPJ0vs6T1SxONHHw.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(uv, s);
  })();

app/views/layouts/application.html.slim
doctype 5
html lang="#{I18n.locale}" xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml"
  head
    title
      - if @title
        == "#{@title}#{' · ' if @title}#{::Configuration[:company_name]}"
      - else
        == "#{yield :title} · #{::Configuration[:company_name]}"
    meta charset='utf-8'
    meta name="robots" content="index, follow"
    meta name="author" content="Engage"
    - if content_for? :meta_tags
      /project specific meta tags
      = yield :meta_tags
    - else
      /meta tags for the whole site
      meta property="og:title" content=t('site.title')
      meta property="og:type" content='cause'
      meta property="og:url" content==(request.protocol + request.host_with_port)
      meta property="og:image" content==(request.protocol + request.host_with_port + asset_path('catarse/logo-fb.jpg'))
      meta property="og:site_name" content=::Configuration[:company_name]
      meta property="fb:app_id" content=Configuration['site.facebook_app_id']
      meta property="og:description" content==(t('projects.index_header.title') + '. ' +  t('projects.index_header.subtitle'))

    = stylesheet_link_tag 'application', :media => 'screen, projection'
    /[if lt IE 9]
      = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"
    = yield :js_templates
    = javascript_include_tag 'application'
    = csrf_meta_tag
    link rel='shortcut icon' href="/assets/favicon.ico"
    = render '/layouts/analytics'

  body[id="platform" data-namespace="#{namespace}" data-controller="#{controller_name}" data-action="#{action_name}" data-locale="#{I18n.locale}" data-user="#{current_user.to_json}"]
    = render_facebook_sdk
    = render partial: 'layouts/flash', locals: { flash: flash } unless flash.empty?
    = render 'layouts/locales'

    = render 'layouts/header'
    #main_content[data-controller-class=controller.class.name.downcase data-controller-name=controller.controller_name.downcase data-action=controller.action_name.downcase data-locale="#{I18n.locale}" data-user="#{current_user.to_json}"]
      =yield
    #myModal.modal.fade
    #footer
      .container.footer
        .content
          .info
            h3= t('footer.titles.info')
            ul
              li= link_to t('footer.links.about'), about_path
              li= link_to t('footer.links.how_works'), guidelines_path, id: 'guidelines_modal'
              li= link_to t('footer.links.faq'), faq_path
              li= link_to t('footer.links.terms'), t('footer.links.terms_link')
              li= link_to t('footer.links.policy'), t('footer.links.policy_link')
              li= link_to t('footer.links.contact'), "javascript:UserVoice.showPopupWidget({widget_key: 'JcDWrWW6tw6G4htPbGmqDA'});"

          .opendata
            h3= t('footer.titles.opendata')
            ul
              li
                h5= statistics.total_backers
                p= t('footer.stats.backers')
              li
                h5= statistics.total_backs
                p= t('footer.stats.backs')
              li
                h5= number_to_currency statistics.total_backed, :unit => 'R$', :precision => 0, :delimiter => '.'
                p= t('footer.stats.total_backed')
              li
                h5= statistics.total_users
                p= t('footer.stats.users')
              li
                h5= statistics.total_projects_success
                p= t('footer.stats.funded_projects')
              li
                h5= statistics.total_projects_online
                p= t('footer.stats.active_projects')

          .social
            h3= t('footer.titles.social')
            .twitter
              = link_to "Follow @#{Configuration['twitter_username']}", "http://twitter.com/#{Configuration['twitter_username']}", :class => 'twitter-follow-button', :"data-button"=>"blue", :"data-text-color" => "#ffffff", :"data-link-color"=>"#fffffff", :"data-width" => "224px"
            .facebook
              = render_facebook_like href: "#{Configuration['facebook_url']}", width: "171"
            h3.newsletter= t('footer.titles.newsletter')
            = form_tag "#{Configuration['mailchimp_url']}", id: 'mailee-form', method: 'post' do
              = text_field_tag 'EMAIL', nil, placeholder: 'email@email.com', label: 'email'
              = submit_tag "#{t('newsletter_subscribe')}"
          .clearfix
    #logos
      .multide
        = link_to '#' do
          = image_tag('catarse/multide_logo55x36.png', :target => '_blank', :alt => 'MULTIDE')
      .comum
        = link_to 'http://comum.cc', :target => '_blank' do
          = image_tag('catarse/comum_logo127x27.png', :alt => 'COMUM')
      .power
        = link_to 'http://engage.is', :target => '_blank' do
          = image_tag('catarse/power_logo200x43.png', :alt => 'POWER TO THE CROWD')
    = render '/layouts/uservoice'

app/views/layouts/email.html.slim
html
  head
    meta content="text/html; charset=utf-8" http-equiv="Content-Type"
    title= message.subject
  body
    div style="background-image: url(http://gallery.mailchimp.com/9d9950758917a323093e71034/images/background.jpg); background-repeat:repeat; margin:0px;padding: 0px; width: 700px;float: left"
      div style="width: 600px;padding-left: 18px; float:left"
        img src="http://gallery.mailchimp.com/ebfcd0d16dbb0001a0bea3639/images/logo_system.png" width="179px" height="45px" style="float: left; margin-left: 20px; margin-top: 30px"

        div style="width: 599px;height: 68px;float: left; background:url(http://gallery.mailchimp.com/ebfcd0d16dbb0001a0bea3639/images/header_system.png); margin-top: 30px;margin-left: 6px"
          h3 style="color: #ee5192; font-size: 18px;margin-left: 60px;float: left;font-family:Helvetica, Arial, Sans-serif;margin-top: 32px; margin-bottom: 0px; font-style: normal; "
            = @header || message.subject
        div style="background: url(http://gallery.mailchimp.com/9d9950758917a323093e71034/images/back_box.jpg);background-repeat: repeat-y; width: 620px; float: left;"
          #content
            div style="font-family: Helvetica, Arial, Sans-serif;color: #5d5d5d; font-size: 13px; line-height: 21px;width: 513px; margin-left: 60px; font-style:normal; "
              br
              = yield
        div style="background: url(http://gallery.mailchimp.com/9d9950758917a323093e71034/images/close_box2.png); width: 589px; height: 19px;float: left;margin-left: 15px"
        div style="float: right; margin-top: 10px; margin-bottom: 30px; height: 25px;width: 100px;"
          a href="http://www.facebook.com/Catarse.me" style="float: right; width: 25px; height: 25px; margin-left: 5px; margin-right: 5px;" target="_blank"
            img alt="Facebook" height="25" src="http://gallery.mailchimp.com/9d9950758917a323093e71034/images/icon_facebook.gif" width="25"
          a href="http://twitter.com/Catarse_" style="float: right; width: 25px; height: 25px; margin-left: 5px; margin-right: 5px;" target="_blank"
            img alt="Twitter" height="25" src="http://gallery.mailchimp.com/9d9950758917a323093e71034/images/icon_twitter.gif" width="25"

app/views/layouts/embed.html.slim
doctype 5
html lang="#{I18n.locale}" xmlns:fb="http://ogp.me/ns/fb#"
  head
    meta charset='utf-8'
    title= "#{@title}#{' · ' if @title}#{::Configuration[:company_name]}"
    = stylesheet_link_tag 'application', :media => 'screen, projection'
    /[if lt IE 9]
      = javascript_include_tag "http://html5shiv.googlecode.com/svn/trunk/html5.js"
    = csrf_meta_tag
    link rel='shortcut icon' href="/images/favicon.ico"
    = render '/layouts/analytics'
  body#platform
    = yield